/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

/**
 *
 * @author Luis
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JPanel();
        combo_indices = new javax.swing.JComboBox();
        rbtn_ascendente = new javax.swing.JRadioButton();
        rbtn_descendente = new javax.swing.JRadioButton();
        panel_interno = new javax.swing.JPanel();
        rbtn_insercion = new javax.swing.JRadioButton();
        rbtn_burbuja = new javax.swing.JRadioButton();
        rbtn_shellsort = new javax.swing.JRadioButton();
        rbtn_mergesort = new javax.swing.JRadioButton();
        rbtn_quicksort = new javax.swing.JRadioButton();
        panel_externo = new javax.swing.JPanel();
        rbtn_directa = new javax.swing.JRadioButton();
        rbtn_natural = new javax.swing.JRadioButton();
        panel_resultados = new javax.swing.JPanel();
        scrollpane_tabla = new javax.swing.JScrollPane();
        tabla_resultados = new javax.swing.JTable();
        lb_valor = new javax.swing.JLabel();
        tf_valor = new javax.swing.JTextField();
        lb_criterio_ordenamiento = new javax.swing.JLabel();
        combo_signos = new javax.swing.JComboBox();
        btn_limpiar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_principal.setBorder(javax.swing.BorderFactory.createTitledBorder("Índice"));

        combo_indices.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "Índice Nacional de Precios al consumidor, Variación mensual",
            "Índice Nacional de Precios al consumidor, Variación acumulada",
            "Índice Nacional de Precios al consumidor, variación anual",
            "Inflación, Subyacente (nueva definición), Mensual",
            "Inflación, Subyacente (nueva definición), Acumulada en el año",
            "Inflación, Subyacente (nueva definición), Anual",
            "Inflación, No subyacente (nueva definición), Mensual",
            "Inflación, No subyacente (nueva definición), Acumulada en el año",
            "Inflación, No subyacente (nueva definición), Anual",
            "Índice Nacional de Precios al consumidor Canasta básica, ",
            "Variación mensual",
            "Índice Nacional de Precios al consumidor Canasta básica, Variación acumulada",
            "Índice Nacional de Precios al consumidor Canasta básica, Variación anual Inflación, Índice nacional precios productor sin petróleo y sin servicios (INPP), Mensual Inflación, Índice nacional precios productor sin petróleo y sin servicios (INPP), Acumulada en el año Inflación,",
            "Índice nacional precios productor sin petróleo y sin servicios (INPP), Anual",
        }));
        combo_indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_indicesActionPerformed(evt);
            }
        });

        rbtn_ascendente.setText("Ascendente");
        rbtn_ascendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_ascendenteActionPerformed(evt);
            }
        });

        rbtn_descendente.setText("Descendente");

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addComponent(rbtn_ascendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn_descendente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addComponent(combo_indices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_indices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_ascendente)
                    .addComponent(rbtn_descendente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_interno.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenamiento interno"));

        rbtn_insercion.setText("Inserción");
        rbtn_insercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_insercionActionPerformed(evt);
            }
        });

        rbtn_burbuja.setText("Burbuja");

        rbtn_shellsort.setText("ShellSort");

        rbtn_mergesort.setText("MergeSort");
        rbtn_mergesort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_mergesortActionPerformed(evt);
            }
        });

        rbtn_quicksort.setText("QuickSort");
        rbtn_quicksort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_quicksortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_internoLayout = new javax.swing.GroupLayout(panel_interno);
        panel_interno.setLayout(panel_internoLayout);
        panel_internoLayout.setHorizontalGroup(
            panel_internoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_internoLayout.createSequentialGroup()
                .addComponent(rbtn_insercion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_burbuja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn_shellsort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtn_mergesort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtn_quicksort)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        panel_internoLayout.setVerticalGroup(
            panel_internoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_internoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbtn_insercion)
                .addComponent(rbtn_burbuja)
                .addComponent(rbtn_shellsort)
                .addComponent(rbtn_mergesort)
                .addComponent(rbtn_quicksort))
        );

        panel_externo.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenamiento externo"));

        rbtn_directa.setText("Directa");

        rbtn_natural.setText("Natural");
        rbtn_natural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_naturalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_externoLayout = new javax.swing.GroupLayout(panel_externo);
        panel_externo.setLayout(panel_externoLayout);
        panel_externoLayout.setHorizontalGroup(
            panel_externoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_externoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_directa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtn_natural)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panel_externoLayout.setVerticalGroup(
            panel_externoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_externoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbtn_directa)
                .addComponent(rbtn_natural))
        );

        panel_resultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        tabla_resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor del índice"
            }
        ));
        scrollpane_tabla.setViewportView(tabla_resultados);

        javax.swing.GroupLayout panel_resultadosLayout = new javax.swing.GroupLayout(panel_resultados);
        panel_resultados.setLayout(panel_resultadosLayout);
        panel_resultadosLayout.setHorizontalGroup(
            panel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane_tabla)
                .addContainerGap())
        );
        panel_resultadosLayout.setVerticalGroup(
            panel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        lb_valor.setText("Valor");

        lb_criterio_ordenamiento.setText("Criterio de ordenamiento");

        combo_signos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Item 2", "Item 3", "Item 4" }));
        combo_signos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_signosActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_limpiar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lb_valor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_valor))
                                .addComponent(panel_interno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panel_externo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lb_criterio_ordenamiento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(combo_signos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_interno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_externo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_valor)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_criterio_ordenamiento)
                    .addComponent(combo_signos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpiar)
                    .addComponent(btn_buscar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_insercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_insercionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_insercionActionPerformed

    private void rbtn_mergesortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_mergesortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_mergesortActionPerformed

    private void rbtn_naturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_naturalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_naturalActionPerformed

    private void combo_signosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_signosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_signosActionPerformed

    private void rbtn_ascendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_ascendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_ascendenteActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void rbtn_quicksortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_quicksortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_quicksortActionPerformed

    private void combo_indicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_indicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_indicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JComboBox combo_indices;
    private javax.swing.JComboBox combo_signos;
    private javax.swing.JLabel lb_criterio_ordenamiento;
    private javax.swing.JLabel lb_valor;
    private javax.swing.JPanel panel_externo;
    private javax.swing.JPanel panel_interno;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JPanel panel_resultados;
    private javax.swing.JRadioButton rbtn_ascendente;
    private javax.swing.JRadioButton rbtn_burbuja;
    private javax.swing.JRadioButton rbtn_descendente;
    private javax.swing.JRadioButton rbtn_directa;
    private javax.swing.JRadioButton rbtn_insercion;
    private javax.swing.JRadioButton rbtn_mergesort;
    private javax.swing.JRadioButton rbtn_natural;
    private javax.swing.JRadioButton rbtn_quicksort;
    private javax.swing.JRadioButton rbtn_shellsort;
    private javax.swing.JScrollPane scrollpane_tabla;
    private javax.swing.JTable tabla_resultados;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables
}
